name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y php php-cli php-mysql unzip
        composer install

    - name: Start MySQL service
      run: |
        sudo systemctl start mysql
        sudo mysql -e "CREATE DATABASE IF NOT EXISTS quiz_pengupil;"
        sudo mysql -e "GRANT ALL PRIVILEGES ON quiz_pengupil.* TO 'root'@'localhost' IDENTIFIED BY '';"

    - name: Start PHP server
      run: |
        php -S 127.0.0.1:8000 -t . > server.log 2>&1 &

    - name: Wait for server to start
      run: sleep 10

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager pytest

    - name: Start Selenium WebDriver (Chrome)
      run: |
        sudo apt update
        sudo apt install -y google-chrome-stable

    - name: Run Selenium Tests
      run: python tests/test_login_register.py

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: selenium-test-results
        path: test-results/

    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: selenium-test-logs
        path: test-results/test_log.txt