name: OTF Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Functional Test
    permissions: write-all
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: quiz_pengupil
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # Stage 1: Persiapan Lingkungan
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up Docker network
        run: docker network create --driver bridge isolated

      # Stage 2: Build dan Jalankan Aplikasi PHP
      - name: Build PHP application
        run: docker build -t my-php-site:latest .

      - name: Run PHP application
        run: docker run --network=isolated -d -p 80:80 --name docker-apache -t my-php-site:latest

      # Stage 3: Persiapan MySQL
      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h127.0.0.1 -uroot -proot --silent; do
            echo "Waiting for MySQL..."
            sleep 1
          done

      - name: Import database
        run: |
          mysql -h127.0.0.1 -uroot -proot quiz_pengupil < db/quiz_pengupil.sql

      # Stage 4: Persiapan Selenium
      - name: Run Selenium Standalone Firefox
        run: |
          docker run --network=isolated -d -p 4444:4444 -p 7900:7900 -v /dev/shm:/dev/shm --name firefox-standalone selenium/standalone-firefox:latest

      - name: Wait for Selenium Hub
        run: sh wait.sh

      # Stage 5: Jalankan Pengujian
      - name: Install Selenium client
        run: pip install -U selenium

      - name: Run Selenium tests
        run: python tests/test_login_register.py

      # Stage 6: Pembersihan
      - name: Stop PHP application container
        run: docker stop docker-apache

      - name: Stop Selenium container
        run: docker stop firefox-standalone

      - name: Remove Docker network
        run: docker network rm isolated