name: CI/CD Pipeline for PHP Application with Selenium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest

      - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo mysql -e "CREATE DATABASE quiz_pengupil;"
          sudo mysql -e "CREATE USER 'root'@'localhost' IDENTIFIED BY '';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON quiz_pengupil.* TO 'root'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"
          sudo mysql quiz_pengupil < db/quiz_pengupil.sql

      - name: Set up PHP
        run: |
          sudo apt-get install -y php-cli php-mysql
          php -S localhost:8000 -t . &
          echo "PHP server started on port 8000"

      - name: Set up ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Run Selenium tests
        run: |
          python -m pytest tests/test_login_register.py -v