name: OTF Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: quiz_pengupil
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # Stage 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Stage 2: Set up PHP and dependencies
      - name: Set up PHP and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y php php-cli php-mysql

      # Stage 3: Start local PHP server
      - name: Start local server
        run: php -S localhost:8000 -t . &

      # Stage 4: Wait for MySQL to be ready
      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h127.0.0.1 -uroot -proot --silent; do
            echo "Waiting for MySQL..."
            sleep 1
          done

      # Stage 5: Import database
      - name: Import database
        run: |
          mysql -h127.0.0.1 -uroot -proot quiz_pengupil < db/quiz_pengupil.sql

      # Stage 6: Run Selenium tests
      - name: Run Selenium tests
        run: |
          pip install -U selenium
          python -m unittest discover tests/