name: OTF Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Functional Test
    permissions: write-all
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: quiz_pengupil
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Build and run PHP application
        run: |
          docker build -t my-php-site:latest .
          docker run -d -p 80:80 --name docker-apache -t my-php-site:latest

      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h127.0.0.1 -uroot -proot --silent; do
            echo "Waiting for MySQL..."
            sleep 1
          done

      - name: Import database
        run: |
          mysql -h127.0.0.1 -uroot -proot quiz_pengupil < db/quiz_pengupil.sql

      - name: Run Selenium tests
        run: |
          docker run --network=host -d -p 4444:4444 -p 7900:7900 -v /dev/shm:/dev/shm --name firefox-standalone selenium/standalone-firefox:latest
          sh wait.sh
          pip install -U selenium
          python tests/test_login_register.py

      - name: Stop containers
        run: |
          docker stop docker-apache
          docker stop firefox-standalone